version: '3.8'
services:
  jenkins:
    # --- CHANGE IS HERE ---
    # Instead of 'image', we use 'build' to point to your Dockerfile
    build: ./custom_jenkins
    container_name: jenkins-dind
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
